### PR TITLE
added-careers-page

### PR DESCRIPTION
**Pull request by vashukashyap**
## what this PR do?
this PR is regarding the implementation of career page

### CODE REVIEW

**Comment by Vandit1604** [comment]
Kaafi bhari kaam

**Comment by Vandit1604** [comment]
Changes kardey jaldi merge marna hai boii

**Comment by Vandit1604** [comment]
rebase marlio

**Comment by arjunomray** [comment]
fixes: #14

**Comment by Vandit1604** [comment]
@vashukashyap 
Looks good some nits from my side

- The Careers heading is really large in size compared to other pages. Reduce it size for uniformity
- How about 5 cards columns since there's so much dead space on the sides with 3 columns

**Comment by arjunomray** [comment]
lgtm

**Pull request merged**
